//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Desktop.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeManagement.Desktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +  Mitarbeiter hinzufügen.
        /// </summary>
        internal static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Mitarbeiter anlegen (Strg+N).
        /// </summary>
        internal static string AddEmployeeTooltip {
            get {
                return ResourceManager.GetString("AddEmployeeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiterverwaltung.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        internal static string ColumnActions {
            get {
                return ResourceManager.GetString("ColumnActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abteilung.
        /// </summary>
        internal static string ColumnDepartment {
            get {
                return ResourceManager.GetString("ColumnDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string ColumnEmail {
            get {
                return ResourceManager.GetString("ColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrittsdatum.
        /// </summary>
        internal static string ColumnHireDate {
            get {
                return ResourceManager.GetString("ColumnHireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        internal static string ConflictBack {
            get {
                return ResourceManager.GetString("ConflictBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Mitarbeiter wurde inzwischen geändert.
        /// </summary>
        internal static string ConflictHeading {
            get {
                return ResourceManager.GetString("ConflictHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu laden.
        /// </summary>
        internal static string ConflictReload {
            get {
                return ResourceManager.GetString("ConflictReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein anderer Benutzer hat diesen Mitarbeiter geändert, nachdem Sie ihn geöffnet haben. Ihre Änderungen wurden nicht gespeichert.
        ///
        ///„Neu laden“ zeigt die aktuellen Daten an, Ihre Eingaben gehen dabei verloren. „Zurück“ lässt Ihre Eingaben stehen..
        /// </summary>
        internal static string ConflictText {
            get {
                return ResourceManager.GetString("ConflictText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Mitarbeiter wurde inzwischen von einem anderen Benutzer geändert und deshalb nicht gelöscht. Bitte prüfen Sie die aktuellen Daten..
        /// </summary>
        internal static string DeleteConflict {
            get {
                return ResourceManager.GetString("DeleteConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiter löschen?.
        /// </summary>
        internal static string DeleteHeading {
            get {
                return ResourceManager.GetString("DeleteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Mitarbeiter wurde bereits gelöscht..
        /// </summary>
        internal static string DeleteNotFound {
            get {
                return ResourceManager.GetString("DeleteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to „{0}“ wird endgültig gelöscht..
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen (Entf).
        /// </summary>
        internal static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen ….
        /// </summary>
        internal static string DepartmentPlaceholder {
            get {
                return ResourceManager.GetString("DepartmentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwerfen.
        /// </summary>
        internal static string DiscardConfirm {
            get {
                return ResourceManager.GetString("DiscardConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen verwerfen?.
        /// </summary>
        internal static string DiscardHeading {
            get {
                return ResourceManager.GetString("DiscardHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter bearbeiten.
        /// </summary>
        internal static string DiscardKeepEditing {
            get {
                return ResourceManager.GetString("DiscardKeepEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Änderungen wurden noch nicht gespeichert..
        /// </summary>
        internal static string DiscardText {
            get {
                return ResourceManager.GetString("DiscardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese E-Mail-Adresse wird bereits von einem anderen Mitarbeiter verwendet..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten (Enter).
        /// </summary>
        internal static string EditTooltip {
            get {
                return ResourceManager.GetString("EditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mitarbeiter.
        /// </summary>
        internal static string EmployeeCount {
            get {
                return ResourceManager.GetString("EmployeeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Mitarbeiter wurde inzwischen gelöscht. Die Liste wird aktualisiert..
        /// </summary>
        internal static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Mitarbeiter gefunden..
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbankverbindung ist nicht konfiguriert.
        ///
        ///Bitte tragen Sie den Connection String in die Datei appsettings.Local.json ein (siehe README). Die Anwendung wird beendet..
        /// </summary>
        internal static string ErrorConfigurationInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Zugriff auf die Datenbank ist ein Fehler aufgetreten. Bitte prüfen Sie, ob die Datenbank erreichbar ist, und versuchen Sie es erneut.
        ///
        ///Details stehen in der Log-Datei..
        /// </summary>
        internal static string ErrorDatabaseUnavailable {
            get {
                return ResourceManager.GetString("ErrorDatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anwendung konnte nicht gestartet werden. Details stehen in der Log-Datei..
        /// </summary>
        internal static string ErrorStartupFailed {
            get {
                return ResourceManager.GetString("ErrorStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unerwarteter Fehler ist aufgetreten. Details stehen in der Log-Datei..
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Abteilungen.
        /// </summary>
        internal static string FilterAllDepartments {
            get {
                return ResourceManager.GetString("FilterAllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Seite.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiter hinzufügen.
        /// </summary>
        internal static string FormTitleAdd {
            get {
                return ResourceManager.GetString("FormTitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiter bearbeiten.
        /// </summary>
        internal static string FormTitleEdit {
            get {
                return ResourceManager.GetString("FormTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abteilung.
        /// </summary>
        internal static string LabelDepartment {
            get {
                return ResourceManager.GetString("LabelDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrittsdatum.
        /// </summary>
        internal static string LabelHireDate {
            get {
                return ResourceManager.GetString("LabelHireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Seite.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste Seite.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite {0} von {1}.
        /// </summary>
        internal static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pro Seite.
        /// </summary>
        internal static string PageSizeOption {
            get {
                return ResourceManager.GetString("PageSizeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorherige Seite.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren (F5).
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt keine Änderungen zum Speichern..
        /// </summary>
        internal static string SaveNoChangesHint {
            get {
                return ResourceManager.GetString("SaveNoChangesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie zuerst alle Pflichtfelder (*) aus..
        /// </summary>
        internal static string SaveRequiredFieldsHint {
            get {
                return ResourceManager.GetString("SaveRequiredFieldsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name oder E-Mail suchen ….
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiter wurde angelegt..
        /// </summary>
        internal static string StatusCreated {
            get {
                return ResourceManager.GetString("StatusCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiter wurde gelöscht..
        /// </summary>
        internal static string StatusDeleted {
            get {
                return ResourceManager.GetString("StatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen wurden gespeichert..
        /// </summary>
        internal static string StatusSaved {
            get {
                return ResourceManager.GetString("StatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die gewählte Abteilung existiert nicht mehr. Bitte wählen Sie eine andere aus..
        /// </summary>
        internal static string ValidationDepartmentNotFound {
            get {
                return ResourceManager.GetString("ValidationDepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Abteilung aus..
        /// </summary>
        internal static string ValidationDepartmentRequired {
            get {
                return ResourceManager.GetString("ValidationDepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige E-Mail-Adresse ein, z. B. vorname.nachname@firma.com..
        /// </summary>
        internal static string ValidationEmailInvalid {
            get {
                return ResourceManager.GetString("ValidationEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine E-Mail-Adresse ein..
        /// </summary>
        internal static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse darf höchstens {0} Zeichen lang sein..
        /// </summary>
        internal static string ValidationEmailTooLong {
            get {
                return ResourceManager.GetString("ValidationEmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Vornamen ein..
        /// </summary>
        internal static string ValidationFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorname darf höchstens {0} Zeichen lang sein..
        /// </summary>
        internal static string ValidationFirstNameTooLong {
            get {
                return ResourceManager.GetString("ValidationFirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Eintrittsdatum darf nicht vor dem {0} liegen..
        /// </summary>
        internal static string ValidationHireDateTooEarly {
            get {
                return ResourceManager.GetString("ValidationHireDateTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Eintrittsdatum darf höchstens ein Jahr in der Zukunft liegen..
        /// </summary>
        internal static string ValidationHireDateTooFarInFuture {
            get {
                return ResourceManager.GetString("ValidationHireDateTooFarInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Nachnamen ein..
        /// </summary>
        internal static string ValidationLastNameRequired {
            get {
                return ResourceManager.GetString("ValidationLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Nachname darf höchstens {0} Zeichen lang sein..
        /// </summary>
        internal static string ValidationLastNameTooLong {
            get {
                return ResourceManager.GetString("ValidationLastNameTooLong", resourceCulture);
            }
        }
    }
}
