//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Desktop.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeManagement.Desktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiterverwaltung.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbankverbindung ist nicht konfiguriert.
        ///
        ///Bitte tragen Sie den Connection String in die Datei appsettings.Local.json ein (siehe README). Die Anwendung wird beendet..
        /// </summary>
        internal static string ErrorConfigurationInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Zugriff auf die Datenbank ist ein Fehler aufgetreten. Bitte prüfen Sie, ob die Datenbank erreichbar ist, und versuchen Sie es erneut.
        ///
        ///Details stehen in der Log-Datei..
        /// </summary>
        internal static string ErrorDatabaseUnavailable {
            get {
                return ResourceManager.GetString("ErrorDatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anwendung konnte nicht gestartet werden. Details stehen in der Log-Datei..
        /// </summary>
        internal static string ErrorStartupFailed {
            get {
                return ResourceManager.GetString("ErrorStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unerwarteter Fehler ist aufgetreten. Details stehen in der Log-Datei..
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die gewählte Abteilung existiert nicht mehr. Bitte wählen Sie eine andere aus..
        /// </summary>
        internal static string ValidationDepartmentNotFound {
            get {
                return ResourceManager.GetString("ValidationDepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Abteilung aus..
        /// </summary>
        internal static string ValidationDepartmentRequired {
            get {
                return ResourceManager.GetString("ValidationDepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige E-Mail-Adresse ein, z. B. vorname.nachname@firma.com..
        /// </summary>
        internal static string ValidationEmailInvalid {
            get {
                return ResourceManager.GetString("ValidationEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine E-Mail-Adresse ein..
        /// </summary>
        internal static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse darf höchstens {0} Zeichen lang sein..
        /// </summary>
        internal static string ValidationEmailTooLong {
            get {
                return ResourceManager.GetString("ValidationEmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Vornamen ein..
        /// </summary>
        internal static string ValidationFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorname darf höchstens {0} Zeichen lang sein..
        /// </summary>
        internal static string ValidationFirstNameTooLong {
            get {
                return ResourceManager.GetString("ValidationFirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Eintrittsdatum darf nicht vor dem {0} liegen..
        /// </summary>
        internal static string ValidationHireDateTooEarly {
            get {
                return ResourceManager.GetString("ValidationHireDateTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Eintrittsdatum darf höchstens ein Jahr in der Zukunft liegen..
        /// </summary>
        internal static string ValidationHireDateTooFarInFuture {
            get {
                return ResourceManager.GetString("ValidationHireDateTooFarInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Nachnamen ein..
        /// </summary>
        internal static string ValidationLastNameRequired {
            get {
                return ResourceManager.GetString("ValidationLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Nachname darf höchstens {0} Zeichen lang sein..
        /// </summary>
        internal static string ValidationLastNameTooLong {
            get {
                return ResourceManager.GetString("ValidationLastNameTooLong", resourceCulture);
            }
        }
    }
}
